name: lint

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - '**/README.md'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Check Python version
        run: python --version
      - name: Install
        run: |
          python -m pip install --upgrade pip
          make install-dev
      - name: Format
        run: make fmt
      - name: Lint
        run: make lint